site_name: gNext
theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
#      primary: 5DC9E2
#      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
#      primary: teal
#      accent: amber
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.sections
    - content.code.copy
    - content.code.annotate
repo_name: meteran/gnext
repo_url: https://github.com/meteran/gnext
extra_css:
  - stylesheets/colors.css
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
nav:
  - index.md
  - first-steps.md
  - User Guide:
      - user-guide/request-body.md
      - user-guide/query-parameters.md
      - user-guide/path-parameters.md
      - user-guide/headers.md
      - user-guide/response-status-code.md
      - user-guide/endpoint-groups.md
      - user-guide/middlewares.md
      - user-guide/error-handling.md
  - Advanced:
      - advanced-guide/gin-context.md
plugins:
  - termynal
  - search
